// <auto-generated />
using System;
using Gentle.EntityFramework.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySql.EntityFrameworkCore.Metadata;

#nullable disable

namespace Gentle.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20260326063500_AddMeterRecordAndUtilityBill")]
    partial class AddMeterRecordAndUtilityBill
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("MySQL:Charset", "utf8mb4")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Gentle.Core.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("ActualAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BillStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RentalRecordId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RentalRecordId");

                    b.HasIndex("RoomId");

                    b.ToTable("bill");
                });

            modelBuilder.Entity("Gentle.Core.Entities.CollectionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("CollectResult")
                        .HasColumnType("int");

                    b.Property<DateTime>("CollectDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("GraceUntil")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("collection_record");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PropertyPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("community");
                });

            modelBuilder.Entity("Gentle.Core.Entities.MeterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ElectricFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ElectricReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectricUsage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("MeterDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PrevElectricReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrevWaterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("WaterFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WaterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterUsage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("meter_record");
                });

            modelBuilder.Entity("Gentle.Core.Entities.RentalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("BalanceRefund")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CheckInDeposit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CheckOutDepositDeduction")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepositStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalWaterReading")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FinalElectricReading")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LeaseType")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RenterId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RenterId");

                    b.HasIndex("RoomId");

                    b.ToTable("rental_record");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("CommunityId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ElectricPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("RentPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RoomType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("WaterPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("room");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdCard")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("tenant");
                });

            modelBuilder.Entity("Gentle.Core.Entities.UtilityBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BillTenantId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ElectricFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ElectricUsage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MeterRecordId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("WaterFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WaterUsage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillTenantId");

                    b.HasIndex("MeterRecordId")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.ToTable("utility_bill");
                });

            modelBuilder.Entity("Gentle.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Bill", b =>
                {
                    b.HasOne("Gentle.Core.Entities.RentalRecord", "RentalRecord")
                        .WithMany("Bills")
                        .HasForeignKey("RentalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gentle.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalRecord");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Gentle.Core.Entities.CollectionRecord", b =>
                {
                    b.HasOne("Gentle.Core.Entities.Bill", "Bill")
                        .WithMany("CollectionRecords")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Gentle.Core.Entities.MeterRecord", b =>
                {
                    b.HasOne("Gentle.Core.Entities.Room", "Room")
                        .WithMany("MeterRecords")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Gentle.Core.Entities.RentalRecord", b =>
                {
                    b.HasOne("Gentle.Core.Entities.Tenant", "Renter")
                        .WithMany("RentalRecords")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gentle.Core.Entities.Room", "Room")
                        .WithMany("RentalRecords")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Renter");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Room", b =>
                {
                    b.HasOne("Gentle.Core.Entities.Community", "Community")
                        .WithMany("Rooms")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Gentle.Core.Entities.UtilityBill", b =>
                {
                    b.HasOne("Gentle.Core.Entities.Tenant", "BillTenant")
                        .WithMany()
                        .HasForeignKey("BillTenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gentle.Core.Entities.MeterRecord", "MeterRecord")
                        .WithOne("UtilityBill")
                        .HasForeignKey("Gentle.Core.Entities.UtilityBill", "MeterRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gentle.Core.Entities.Room", "Room")
                        .WithMany("UtilityBills")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillTenant");

                    b.Navigation("MeterRecord");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Bill", b =>
                {
                    b.Navigation("CollectionRecords");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Community", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Gentle.Core.Entities.MeterRecord", b =>
                {
                    b.Navigation("UtilityBill");
                });

            modelBuilder.Entity("Gentle.Core.Entities.RentalRecord", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Room", b =>
                {
                    b.Navigation("MeterRecords");

                    b.Navigation("RentalRecords");

                    b.Navigation("UtilityBills");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Tenant", b =>
                {
                    b.Navigation("RentalRecords");
                });
        }
    }
}
