// <auto-generated />
using System;
using Gentle.EntityFramework.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gentle.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Gentle.Core.Entities.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PropertyPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Community");
                });

            modelBuilder.Entity("Gentle.Core.Entities.MeterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ElectricFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ElectricReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectricUsage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("MeterDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PrevElectricReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrevWaterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("WaterFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WaterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterUsage")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("meter_record");
                });

            modelBuilder.Entity("Gentle.Core.Entities.RentalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CheckOutRemark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DepositDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepositStatus")
                        .HasColumnType("int");

                    b.Property<int>("LeaseType")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RenterId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("RenterId");

                    b.HasIndex("RoomId");

                    b.ToTable("rental_record");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CommunityId")
                        .HasColumnType("int");

                    b.Property<string>("ContractImage")
                        .HasColumnType("longtext");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ElectricPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<decimal>("RentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoomType")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("WaterPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdCard")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("Gentle.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DisplayName = "管理员",
                            IsEnabled = true,
                            PasswordHash = "$2a$11$jJoUNJ0hN/g0UjgEwNszkOKIkoQxPcGGgn8fE1wPZltGx4gIYNVkS",
                            Username = "zhs"
                        });
                });

            modelBuilder.Entity("Gentle.Core.Entities.UtilityBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BillTenantId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ElectricFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ElectricUsage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeterRecordId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("RentalRecordId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("WaterFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WaterUsage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillTenantId");

                    b.HasIndex("MeterRecordId")
                        .IsUnique();

                    b.HasIndex("RentalRecordId");

                    b.HasIndex("RoomId");

                    b.ToTable("utility_bill");
                });

            modelBuilder.Entity("Gentle.Core.Entities.MeterRecord", b =>
                {
                    b.HasOne("Gentle.Core.Entities.Room", "Room")
                        .WithMany("MeterRecords")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Gentle.Core.Entities.RentalRecord", b =>
                {
                    b.HasOne("Gentle.Core.Entities.Tenant", "Renter")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gentle.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Renter");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Room", b =>
                {
                    b.HasOne("Gentle.Core.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Gentle.Core.Entities.UtilityBill", b =>
                {
                    b.HasOne("Gentle.Core.Entities.Tenant", "BillTenant")
                        .WithMany()
                        .HasForeignKey("BillTenantId");

                    b.HasOne("Gentle.Core.Entities.MeterRecord", "MeterRecord")
                        .WithOne("UtilityBill")
                        .HasForeignKey("Gentle.Core.Entities.UtilityBill", "MeterRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gentle.Core.Entities.RentalRecord", "RentalRecord")
                        .WithMany("UtilityBills")
                        .HasForeignKey("RentalRecordId");

                    b.HasOne("Gentle.Core.Entities.Room", "Room")
                        .WithMany("UtilityBills")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillTenant");

                    b.Navigation("MeterRecord");

                    b.Navigation("RentalRecord");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Gentle.Core.Entities.MeterRecord", b =>
                {
                    b.Navigation("UtilityBill");
                });

            modelBuilder.Entity("Gentle.Core.Entities.RentalRecord", b =>
                {
                    b.Navigation("UtilityBills");
                });

            modelBuilder.Entity("Gentle.Core.Entities.Room", b =>
                {
                    b.Navigation("MeterRecords");

                    b.Navigation("UtilityBills");
                });
#pragma warning restore 612, 618
        }
    }
}
